# Generated by Django 2.2.5 on 2019-09-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accumulatedMoney',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='city', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(default='last', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='state', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(default='street', max_length=120),
        ),
    ]
