# Generated by Django 2.2.5 on 2019-09-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_test', '0002_auto_20180405_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_reward',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
