# Generated by Django 2.2.5 on 2019-09-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_test', '0003_quiz_quiz_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='this is description'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='image_url',
            field=models.ImageField(default='img_1', upload_to='question_pics/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_type',
            field=models.CharField(default='this is type', max_length=100),
        ),
    ]
