# Generated by Django 2.2.5 on 2019-09-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_test', '0004_auto_20190916_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_statues',
            field=models.BooleanField(default=False),
        ),
    ]
